version = "3.11.4"
include ".scalafmt-common.conf"
runner.dialect = scala3

project.includePaths = [
  "glob:**/itc/**/*.scala"
  "glob:**/resource/**/*.scala"
]

project.excludePaths = [
  "glob:**/modules/**/*.scala"
]
