services:
  db:
    image: postgres:15
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    volumes:
      # this is necessary for CI but can cause confusion locally, sorry
      - ./docker-init:/docker-entrypoint-initdb.d/
      # Mount migrations for scripts to access
      - ./modules/service/src/main/resources/db/migration/:/docker-entrypoint-initdb.d/odb-migrations/
      # SSO migrations
      - ./modules/sso-service/src/main/resources/db/migration/:/docker-entrypoint-initdb.d/sso-migrations/
      # SSL certificates
      - ./test-cert/server.crt:/var/lib/postgresql/server.crt
      - ./test-cert/server.key:/var/lib/postgresql/server.key
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER:     jimmy
      POSTGRES_PASSWORD: banana
      POSTGRES_DB:       lucuma-odb
  adminer:
    image: shyim/adminerevo
    restart: always
    environment:
      ADMINER_DEFAULT_DRIVER: pgsql
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_USERNAME: jimmy
      ADMINER_DEFAULT_DB: lucuma-odb
    ports:
      - 8686:8080
