// Copyright (c) 2016-2025 Association of Universities for Research in Astronomy, Inc. (AURA)
// For license information see LICENSE or https://opensource.org/licenses/BSD-3-Clause

package lucuma.odb.sequence.gmos.spectroscopy

import cats.Eq
import cats.derived.*
import lucuma.core.enums.GmosAmpGain
import lucuma.core.enums.GmosAmpReadMode
import lucuma.core.enums.GmosRoi
import lucuma.core.enums.GmosXBinning
import lucuma.core.enums.GmosYBinning
import lucuma.core.math.Offset.Q
import lucuma.core.math.Wavelength
import lucuma.core.math.WavelengthDelta
import lucuma.core.math.WavelengthDither
import lucuma.core.model.ExposureTimeMode
import lucuma.core.model.sequence.gmos.GmosCcdMode
import lucuma.core.model.sequence.gmos.GmosFpuMask
import lucuma.core.model.sequence.gmos.longslit.*

/**
 * The science-mode parameters used by the GMOS long slit and MOS, from which a 
 * science sequence may be generated.
 *
 * Both modes are generated by the same code, so everything the generator reads
 * is declared here.  What varies is the fpu, either builtin or a custom mask.
 *
 * `gcalFpu` is the builtin FPU the smart gcal tables are keyed on.  For long slit 
 * they describe the same aperture. For MOS `gcalFpu` is the builtin long slit FPU 
 * equivalent to the custom mask's slit width.
 *
 * @tparam G grating type
 * @tparam L filter type
 * @tparam U builtin FPU type
 */
trait Config[G, L, U] extends Product with Serializable:

  import Config.Common

  def common: Common

  def grating: G

  def filter: Option[L]

  def coverage: WavelengthDelta

  /** The aperture the generated steps carry. */
  def fpuMask: GmosFpuMask[U]

  /** The builtin FPU used to key the smart gcal search. */
  def gcalFpu: U

  def centralWavelength: Wavelength =
    common.centralWavelength

  def exposureTimeMode: ExposureTimeMode =
    common.exposureTimeMode

  def xBin: GmosXBinning =
    explicitXBin.getOrElse(defaultXBin)

  def defaultXBin: GmosXBinning =
    common.defaultXBin

  def explicitXBin: Option[GmosXBinning] =
    common.explicitXBin

  def yBin: GmosYBinning =
    explicitYBin.getOrElse(defaultYBin)

  def defaultYBin: GmosYBinning =
    common.defaultYBin

  def explicitYBin: Option[GmosYBinning] =
    common.explicitYBin

  def ampReadMode: GmosAmpReadMode =
    explicitAmpReadMode.getOrElse(defaultAmpReadMode)

  def defaultAmpReadMode: GmosAmpReadMode =
    DefaultAmpReadMode

  def explicitAmpReadMode: Option[GmosAmpReadMode] =
    common.explicitAmpReadMode

  def ampGain: GmosAmpGain =
    explicitAmpGain.getOrElse(defaultAmpGain)

  def defaultAmpGain: GmosAmpGain =
    DefaultAmpGain

  def explicitAmpGain: Option[GmosAmpGain] =
    common.explicitAmpGain

  def roi: GmosRoi =
    explicitRoi.getOrElse(defaultRoi)

  def defaultRoi: GmosRoi =
    DefaultRoi

  def explicitRoi: Option[GmosRoi] =
    common.explicitRoi

  def wavelengthDithers: List[WavelengthDither] =
    explicitWavelengthDithers.getOrElse(defaultWavelengthDithers)

  def defaultWavelengthDithers: List[WavelengthDither]

  def explicitWavelengthDithers: Option[List[WavelengthDither]] =
    common.explicitWavelengthDithers

  def spatialOffsets: List[Q] =
    explicitSpatialOffsets.getOrElse(defaultSpatialOffsets)

  def defaultSpatialOffsets: List[Q] =
    Config.DefaultSpatialOffsets

  def explicitSpatialOffsets: Option[List[Q]] =
    common.explicitSpatialOffsets

  def ccdMode: GmosCcdMode =
    GmosCcdMode(
      xBin,
      yBin,
      DefaultAmpCount,
      ampGain,
      ampReadMode
    )

  /**
   * Replaces the explicit wavelength dithers, preserving the concrete mode.
   */
  def withWavelengthDithers(dithers: Option[List[WavelengthDither]]): Config[G, L, U]

  /**
   * Replaces the explicit spatial offsets, preserving the concrete mode.
   */
  def withSpatialOffsets(offsets: Option[List[Q]]): Config[G, L, U]

object Config:

  final case class Common(
    centralWavelength:         Wavelength,
    exposureTimeMode:          ExposureTimeMode,
    defaultXBin:               GmosXBinning,
    explicitXBin:              Option[GmosXBinning],
    defaultYBin:               GmosYBinning,
    explicitYBin:              Option[GmosYBinning],
    explicitAmpReadMode:       Option[GmosAmpReadMode],
    explicitAmpGain:           Option[GmosAmpGain],
    explicitRoi:               Option[GmosRoi],
    explicitWavelengthDithers: Option[List[WavelengthDither]],
    explicitSpatialOffsets:    Option[List[Q]]
  ) derives Eq

  // ShortCut 3374
  val DefaultSpatialOffsets: List[Q] =
    List(
      Q.signedDecimalArcseconds.reverseGet(BigDecimal(  0)),
      Q.signedDecimalArcseconds.reverseGet(BigDecimal( 15)),
      Q.signedDecimalArcseconds.reverseGet(BigDecimal(-15))
    )
