receivers:
  otlp:
    protocols:
      http:
        endpoint: 127.0.0.1:4318

processors:
  memory_limiter:
    limit_mib: 400
    spike_limit_mib: 100
    check_interval: 5s
  batch:
    timeout: 5s
    send_batch_size: 512

exporters:
  otlphttp/honeycomb:
    endpoint: "https://api.honeycomb.io"
    headers:
      x-honeycomb-team: "${env:HONEYCOMB_API_KEY}"
  otlphttp/grafana:
    endpoint: "${env:GRAFANA_OTLP_ENDPOINT}"
    headers:
      authorization: "Basic ${env:GRAFANA_OTLP_TOKEN}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/grafana, otlphttp/honeycomb]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/grafana, otlphttp/honeycomb]
