// Copyright (c) 2016-2025 Association of Universities for Research in Astronomy, Inc. (AURA)
// For license information see LICENSE or https://opensource.org/licenses/BSD-3-Clause

package lucuma.odb.sequence
package gmos.mos

import cats.Eq
import cats.derived.*
import lucuma.core.enums.GmosCustomSlitWidth
import lucuma.core.enums.GmosMosAcquisitionType
import lucuma.core.enums.GmosNorthFilter
import lucuma.core.enums.GmosNorthFpu
import lucuma.core.enums.GmosNorthGrating
import lucuma.core.enums.GmosSouthFilter
import lucuma.core.enums.GmosSouthFpu
import lucuma.core.enums.GmosSouthGrating
import lucuma.core.math.Offset.Q
import lucuma.core.math.WavelengthDelta
import lucuma.core.math.WavelengthDither
import lucuma.core.model.Defined
import lucuma.core.model.ToBeDefined
import lucuma.core.model.sequence.gmos.GmosFpuMask
import lucuma.core.util.Enumerated
import lucuma.odb.sequence.gmos.longslit.Config as LongSlitConfig
import lucuma.odb.sequence.gmos.spectroscopy
import lucuma.odb.sequence.gmos.spectroscopy.Config.Common
import lucuma.odb.sequence.syntax.hash.*

import java.io.ByteArrayOutputStream
import java.io.DataOutputStream

/**
 * Configuration for the GMOS MOS science mode.
 *
 * This is GMOS long slit with the builtin FPU replaced by a custom mask and
 * with no acquisition.  The science sequence is generated by the long slit generator
 *
 * @tparam G grating type
 * @tparam L filter type
 * @tparam U the builtin FPU type the custom mask's slit width corresponds to
 */
sealed trait Config[G: Enumerated, L: Enumerated, U] extends spectroscopy.Config[G, L, U]:

  def customMask: GmosFpuMask.Custom

  /**
   * Whether the acquisition image is taken with the mask in or out the light path.
   */
  def acquisitionType: GmosMosAcquisitionType

  def acquisition: AcquisitionConfig[L]

  override def fpuMask: GmosFpuMask[U] =
    customMask

  /**
   * The builtin long slit FPU whose aperture matches the custom mask's slit
   * width. GmosCustomSlitWidth and the builtin long slit FPUs are in 1:1
   * correspondence, which is what lets a MOS observation be calibrated, binned
   * and estimated as a long slit.
   */
  def equivalentFpu: U

  override def gcalFpu: U =
    equivalentFpu

  /**
   * MOS does not nod along the slit by default.
   */
  override def defaultSpatialOffsets: List[Q] =
    Config.DefaultSpatialOffsets

  def hashBytes: Array[Byte] =
    val bao: ByteArrayOutputStream = new ByteArrayOutputStream(256)
    val out: DataOutputStream      = new DataOutputStream(bao)

    out.writeChars(Enumerated[G].tag(grating))
    filter.foreach(f => out.writeChars(Enumerated[L].tag(f)))
    out.writeChars(customMask.slitWidth.tag)
    customMask.mask match
      case ToBeDefined => ()
      case Defined(id) => out.writeLong(id.value.value)
    out.writeInt(centralWavelength.toPicometers.value.value)
    out.writeChars(acquisitionType.tag)
    out.write(exposureTimeMode.hashBytes)
    out.writeChars(xBin.tag)
    out.writeChars(yBin.tag)
    out.writeChars(ampGain.tag)
    out.writeChars(ampReadMode.tag)
    out.writeChars(roi.tag)
    wavelengthDithers.foreach: d =>
      out.writeInt(d.toPicometers.value)
    spatialOffsets.foreach: o =>
      out.writeLong(o.toAngle.toMicroarcseconds)
    out.write(acquisition.hashBytes)

    out.close()
    bao.toByteArray

object Config:

  final case class GmosNorth(
    grating:         GmosNorthGrating,
    filter:          Option[GmosNorthFilter],
    customMask:      GmosFpuMask.Custom,
    acquisitionType: GmosMosAcquisitionType,
    acquisition:     AcquisitionConfig.GmosNorth,
    common:          Common
  ) extends Config[GmosNorthGrating, GmosNorthFilter, GmosNorthFpu] derives Eq:

    override def coverage: WavelengthDelta =
      grating.simultaneousCoverage

    override def equivalentFpu: GmosNorthFpu =
      Config.northFpu(customMask.slitWidth)

    override def defaultWavelengthDithers: List[WavelengthDither] =
      LongSlitConfig.defaultWavelengthDithersNorth(this.grating)

    override def withWavelengthDithers(dithers: Option[List[WavelengthDither]]): GmosNorth =
      copy(common = common.copy(explicitWavelengthDithers = dithers))

    override def withSpatialOffsets(offsets: Option[List[Q]]): GmosNorth =
      copy(common = common.copy(explicitSpatialOffsets = offsets))

  final case class GmosSouth(
    grating:         GmosSouthGrating,
    filter:          Option[GmosSouthFilter],
    customMask:      GmosFpuMask.Custom,
    acquisitionType: GmosMosAcquisitionType,
    acquisition:     AcquisitionConfig.GmosSouth,
    common:          Common
  ) extends Config[GmosSouthGrating, GmosSouthFilter, GmosSouthFpu] derives Eq:

    override def coverage: WavelengthDelta =
      grating.simultaneousCoverage

    override def equivalentFpu: GmosSouthFpu =
      Config.southFpu(customMask.slitWidth)

    override def defaultWavelengthDithers: List[WavelengthDither] =
      LongSlitConfig.defaultWavelengthDithersSouth(this.grating)

    override def withWavelengthDithers(dithers: Option[List[WavelengthDither]]): GmosSouth =
      copy(common = common.copy(explicitWavelengthDithers = dithers))

    override def withSpatialOffsets(offsets: Option[List[Q]]): GmosSouth =
      copy(common = common.copy(explicitSpatialOffsets = offsets))

  val DefaultSpatialOffsets: List[Q] =
    List.empty

  def northFpu(slitWidth: GmosCustomSlitWidth): GmosNorthFpu =
    slitWidth match
      case GmosCustomSlitWidth.CustomWidth_0_25 => GmosNorthFpu.LongSlit_0_25
      case GmosCustomSlitWidth.CustomWidth_0_50 => GmosNorthFpu.LongSlit_0_50
      case GmosCustomSlitWidth.CustomWidth_0_75 => GmosNorthFpu.LongSlit_0_75
      case GmosCustomSlitWidth.CustomWidth_1_00 => GmosNorthFpu.LongSlit_1_00
      case GmosCustomSlitWidth.CustomWidth_1_50 => GmosNorthFpu.LongSlit_1_50
      case GmosCustomSlitWidth.CustomWidth_2_00 => GmosNorthFpu.LongSlit_2_00
      case GmosCustomSlitWidth.CustomWidth_5_00 => GmosNorthFpu.LongSlit_5_00

  def southFpu(slitWidth: GmosCustomSlitWidth): GmosSouthFpu =
    slitWidth match
      case GmosCustomSlitWidth.CustomWidth_0_25 => GmosSouthFpu.LongSlit_0_25
      case GmosCustomSlitWidth.CustomWidth_0_50 => GmosSouthFpu.LongSlit_0_50
      case GmosCustomSlitWidth.CustomWidth_0_75 => GmosSouthFpu.LongSlit_0_75
      case GmosCustomSlitWidth.CustomWidth_1_00 => GmosSouthFpu.LongSlit_1_00
      case GmosCustomSlitWidth.CustomWidth_1_50 => GmosSouthFpu.LongSlit_1_50
      case GmosCustomSlitWidth.CustomWidth_2_00 => GmosSouthFpu.LongSlit_2_00
      case GmosCustomSlitWidth.CustomWidth_5_00 => GmosSouthFpu.LongSlit_5_00
