// Copyright (c) 2016-2026 Association of Universities for Research in Astronomy, Inc. (AURA)
// For license information see LICENSE or https://opensource.org/licenses/BSD-3-Clause

package lucuma.odb.sequence
package gmos.ifu

import cats.Eq
import cats.data.NonEmptyList
import lucuma.core.enums.GmosNorthFilter
import lucuma.core.enums.GmosNorthFpu
import lucuma.core.enums.GmosNorthGrating
import lucuma.core.enums.GmosNorthIfuFpu
import lucuma.core.enums.GmosSouthFilter
import lucuma.core.enums.GmosSouthFpu
import lucuma.core.enums.GmosSouthGrating
import lucuma.core.enums.GmosSouthIfuFpu
import lucuma.core.enums.StepGuideState
import lucuma.core.math.Offset
import lucuma.core.math.WavelengthDelta
import lucuma.core.math.WavelengthDither
import lucuma.core.model.GmosIfuAnalysis
import lucuma.core.model.sequence.TelescopeConfig
import lucuma.core.model.sequence.gmos.GmosFpuMask
import lucuma.core.util.Enumerated
import lucuma.odb.sequence.gmos.longslit.Config as LongSlitConfig
import lucuma.odb.sequence.gmos.spectroscopy
import lucuma.odb.sequence.gmos.spectroscopy.Config.Common
import lucuma.odb.sequence.syntax.hash.*

import java.io.ByteArrayOutputStream
import java.io.DataOutputStream

/**
 * Configuration for the GMOS IFU science mode.
 *
 * This is GMOS long slit with the slit replaced by one of the two IFU
 * apertures, so the science sequence is generated by the same code.  What
 * differs is that the IFU samples a field rather than a slit: it does not nod
 * along a slit, it reads out unbinned, and it carries the sampling geometry the
 * ITC integrates over.
 *
 * @tparam G grating type
 * @tparam L filter type
 * @tparam U builtin FPU type
 */
sealed trait Config[G: Enumerated, L: Enumerated, U: Enumerated] extends spectroscopy.Config[G, L, U]:

  /**
   * The builtin FPU for the chosen IFU aperture: both pseudo-slits, or either one
   * alone.  Never a nod & shuffle unit, which the mode does not offer.
   */
  def builtinFpu: U

  override def fpuMask: GmosFpuMask[U] =
    GmosFpuMask.Builtin(builtinFpu)

  override def gcalFpu: U =
    builtinFpu

  def ifuAnalysis: GmosIfuAnalysis =
    explicitIfuAnalysis.getOrElse(defaultIfuAnalysis)

  def defaultIfuAnalysis: GmosIfuAnalysis =
    GmosIfuAnalysis.Default

  def explicitIfuAnalysis: Option[GmosIfuAnalysis]

  def acquisition: AcquisitionConfig[L]

  def hashBytes: Array[Byte] =
    val bao: ByteArrayOutputStream = new ByteArrayOutputStream(256)
    val out: DataOutputStream      = new DataOutputStream(bao)

    out.writeChars(Enumerated[G].tag(grating))
    filter.foreach(f => out.writeChars(Enumerated[L].tag(f)))
    out.writeChars(Enumerated[U].tag(builtinFpu))
    out.writeInt(centralWavelength.toPicometers.value.value)
    out.write(exposureTimeMode.hashBytes)
    out.writeChars(xBin.tag)
    out.writeChars(yBin.tag)
    out.writeChars(ampGain.tag)
    out.writeChars(ampReadMode.tag)
    out.writeChars(roi.tag)
    ifuAnalysis match
      case GmosIfuAnalysis.Sum(radius)    =>
        out.writeChar(0)
        out.writeLong(radius.toMicroarcseconds)
      case GmosIfuAnalysis.Single(offset) =>
        out.writeChar(1)
        out.writeLong(offset.toMicroarcseconds)
    wavelengthDithers.foreach: d =>
      out.writeInt(d.toPicometers.value)
    telescopeConfigs.toList.foreach: tc =>
      out.writeLong(tc.offset.p.toAngle.toMicroarcseconds)
      out.writeLong(tc.offset.q.toAngle.toMicroarcseconds)
      out.writeChars(tc.guiding.tag)
    out.write(acquisition.hashBytes)

    out.close()
    bao.toByteArray

object Config:

  final case class GmosNorth(
    grating:             GmosNorthGrating,
    filter:              Option[GmosNorthFilter],
    fpu:                 GmosNorthIfuFpu,
    explicitIfuAnalysis: Option[GmosIfuAnalysis],
    acquisition:         AcquisitionConfig.GmosNorth,
    common:              Common,
    telescopeConfigs:    NonEmptyList[TelescopeConfig]
  ) extends Config[GmosNorthGrating, GmosNorthFilter, GmosNorthFpu]:

    override def coverage: WavelengthDelta =
      grating.simultaneousCoverage

    override def builtinFpu: GmosNorthFpu =
      fpu.fpu

    override def defaultWavelengthDithers: List[WavelengthDither] =
      LongSlitConfig.defaultWavelengthDithersNorth(this.grating)

    override def withWavelengthDithers(dithers: Option[List[WavelengthDither]]): GmosNorth =
      copy(common = common.copy(explicitWavelengthDithers = dithers))

    override def withTelescopeConfigs(tcs: NonEmptyList[TelescopeConfig]): GmosNorth =
      copy(telescopeConfigs = tcs)

  object GmosNorth:

    given Eq[GmosNorth] =
      Eq.by: a =>
        (
          a.grating,
          a.filter,
          a.fpu,
          a.explicitIfuAnalysis,
          a.acquisition,
          a.common,
          a.telescopeConfigs
        )

  final case class GmosSouth(
    grating:             GmosSouthGrating,
    filter:              Option[GmosSouthFilter],
    fpu:                 GmosSouthIfuFpu,
    explicitIfuAnalysis: Option[GmosIfuAnalysis],
    acquisition:         AcquisitionConfig.GmosSouth,
    common:              Common,
    telescopeConfigs:    NonEmptyList[TelescopeConfig]
  ) extends Config[GmosSouthGrating, GmosSouthFilter, GmosSouthFpu]:

    override def coverage: WavelengthDelta =
      grating.simultaneousCoverage

    override def builtinFpu: GmosSouthFpu =
      fpu.fpu

    override def defaultWavelengthDithers: List[WavelengthDither] =
      LongSlitConfig.defaultWavelengthDithersSouth(this.grating)

    override def withWavelengthDithers(dithers: Option[List[WavelengthDither]]): GmosSouth =
      copy(common = common.copy(explicitWavelengthDithers = dithers))

    override def withTelescopeConfigs(tcs: NonEmptyList[TelescopeConfig]): GmosSouth =
      copy(telescopeConfigs = tcs)

  object GmosSouth:

    given Eq[GmosSouth] =
      Eq.by: a =>
        (
          a.grating,
          a.filter,
          a.fpu,
          a.explicitIfuAnalysis,
          a.acquisition,
          a.common,
          a.telescopeConfigs
        )

  val DefaultTelescopeConfigs: NonEmptyList[TelescopeConfig] =
    NonEmptyList.one(TelescopeConfig(Offset.Zero, StepGuideState.Enabled))
